apiVersion: apps/v1  
kind: Deployment
metadata: 
  name: deployment-apigateway
spec: 
  selector:
    matchLabels: 
      app: deployment-pod-label-apigateway
  template:
    metadata:
      labels:
        app: deployment-pod-label-apigateway
    spec:
      containers: 
      - name: apigateway 
        image: hivda/apigatewayservicehrm:v03
        resources: 
          requests: 
            cpu: "300m"
            memory: "1024Mi"
          limits:
            cpu: "500m"
            memory: "2048Mi"
        ports: 
        - containerPort: 80
        env:
          - name: CONFIG_SERVER_URL
            value: http://10.116.4.41:8888
