apiVersion: apps/v1  
kind: Deployment
metadata: 
  name: deployment-config
spec: 
  selector:
    matchLabels: 
      app: deployment-pod-label-config
  template:
    metadata:
      labels:
        app: deployment-pod-label-config
    spec:
      containers: 
      - name: config 
        image: hivda/configservergithrm:v01 
        resources: 
          requests: 
            cpu: "300m"
            memory: "1024Mi"
          limits:
            cpu: "500m"
            memory: "2048Mi"
        ports: 
        - containerPort: 8888
        env:
          - name: GIT_PASSWORD
            value: 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
