apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-auth-export-ip
spec:
  selector: 
    app: deployment-pod-label-auth
  type: LoadBalancer
  ports:
    - name: authport
      port: 8080
      targetPort: 8080
