apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-react
spec:
  selector: 
    app: deployment-pod-label-react
  type: LoadBalancer
  ports:
    - name: reactport
      port: 80
      targetPort: 3000
