server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/HRManagementDB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: java8
    password: root

openfeign:
  user-manager-url: http://localhost:8090/api/v1/user
  company-manager-url: http://localhost:9080/api/v1/company

