server:
  port: 9080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hrmanagement
      username: bilgeadmin
      password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: java8
    password: root