server:
  port: 8090
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hrmanagement
      username: bilgeadmin
      password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: java8
    password: root
openfeign:
  auth-manager-url: http://localhost:8080/api/v1/auth